### ISSUE TITLE
Never TODO list

### ISSUE THREAD

**Issue by PedroHLC** [PedroHLC/HEBorn#6]
-	Browser Tabs No-Wrap
-	Restore old, good, filesystem
-	Modal: abstract to recv INPUT/SELECTS/PATH SELECTOR/FILE SELECTOR
-	FileExplorer: Use Modal
-	Review every Style, searching for places where "each" can be used,
-	Add CRT animation
```css
		@keyframes turn-off{
		  0%{
		    transform:scale(1,1.3) translate3d(0,0,0);
		    -webkit-filter:brightness(1);
		    filter:brightness(1);
		    opacity:1;
		  }
		  60%{
		    transform:scale(1.3,0.001) translate3d(0,0,0);
		    -webkit-filter:brightness(10);
		    filter:brightness(10);
		  }
		  100%{
		    animation-timing-function:$ease-in-quint;
		    transform:scale(0.000,0.0001) translate3d(0,0,0);
		    -webkit-filter:brightness(50);
		    filter:brightness(50);
		  }
		}
		.screen{
		  animation: turn-off 0.55s $ease-out-quint;
		  animation-fill-mode:forwards;
		}
```
